version: '3'
services:

  repo-retriever:
    image: zafer/service-repo-retriever:latest
    ports:
      - 8010:8010/tcp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/scorer?useUnicode=true&characterEncoding=UTF8&useSSL=false
    depends_on:
      - db

  content-scorer:
    image: zafer/service-content-scorer:latest
    ports:
      - 8020:8020/tcp
    environment:
      CONTENT_SCORER_BACKEND: http://localhost:8000
      SPRING_REDIS_HOST: localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/scorer?useUnicode=true&characterEncoding=UTF8&useSSL=false

  user-account:
    image: zafer/service-user-account:latest
    ports:
      - 8050:8050/tcp

  client-api:
    image: zafer/service-client-api:latest
    ports:
      - 8030
    deploy:
      replicas: 2
    environment:
      CONTENT_SCORER_BACKEND: http://localhost:8000

  client-web:
    image: zafer/service-client:latest
    stdin_open: true
    tty: true
    ports:
      - 8080:80/tcp
    depends_on:
      - repo-retriever
      - content-scorer
      - client-api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scorer
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
