version: '3'
services:

  repo-retriever:
    image: zafer/service-repo-retriever:latest
    ports:
      - 8010:8010
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.99.100:3306/scorer?useUnicode=true&characterEncoding=UTF8&useSSL=false
    depends_on:
      - db

  content-scorer:
    image: zafer/service-content-scorer:latest
    ports:
      - 8020:8020
    environment:
      SPRING_REDIS_HOST: 192.168.99.100
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.99.100:3306/scorer?useUnicode=true&characterEncoding=UTF8&useSSL=false

  user-account:
    image: zafer/service-user-account:latest
    ports:
      - 8030:8030

  client-api:
    image: zafer/service-client-api:latest
    ports:
      - 8040:8040

  client-web:
    image: zafer/service-client:latest
    ports:
      - 8080:80/tcp
    depends_on:
      - repo-retriever
      - content-scorer
      - client-api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scorer
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
